version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 418295691381.dkr.ecr.us-east-1.amazonaws.com)
      - REPO=418295691381.dkr.ecr.us-east-1.amazonaws.com/samim
      - TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO:$TAG .
      - echo Pushing the Docker image...
      - docker push $REPO:$TAG
  post_build:
    commands:
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"container1","imageUri":"%s"}]' $REPO:$TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
